FROM tensorflow/tensorflow:2.17.0-gpu

RUN pip install --upgrade pip 
# RUN pip install torch torchvision  
RUN pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu126/torch_stable.html

RUN pip install ipykernel pillow
